PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT (COUNT(?restriction) AS ?counter)
WHERE {
    ?restriction a owl:Restriction ;
    ?type ?cardinality .
    VALUES ?type { owl:cardinality owl:minCardinality owl:maxCardinality }
}
