SELECT (COUNT(?restriction) AS ?counter)
WHERE {
    ?restriction a owl:Restriction ;
    ?type [] .
    VALUES ?type { owl:allValuesFrom owl:cardinality owl:qualifiedCardinality owl:hasSelf owl:hasValue owl:maxCardinality owl:maxQualifiedCardinality owl:minCardinality owl:minQualifiedCardinality owl:someValuesFrom }
}
