SELECT DISTINCT ?c ?lbl
WHERE {
  VALUES ?type { owl:Class rdfs:Class }
  ?c a ?type .
  # Gather all labels
  {
    ?c rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?lbl
  }
  UNION
  {
    ?c ?p ?lbl .
    ?p a owl:AnnotationProperty ;
    ?p rdfs:subPropertyOf* rdfs:label .
  }
}
