PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?c
WHERE {
  VALUES ?type { owl:Class rdfs:Class }
  ?c a ?type .
  FILTER NOT EXISTS { 
    { ?c rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel [] }
    UNION
    {
      ?c ?p [] .
      ?p a owl:AnnotationProperty .
    }
  }
  # exclude blank nodes
  FILTER(isIRI(?c))
  # Exclude deprecated classes
  FILTER NOT EXISTS {
    ?c owl:deprecated ?isDeprecated .
    FILTER (?isDeprecated = true || LCASE(STR(?isDeprecated)) = "true" || STR(?isDeprecated) = "1")
  }
}

