PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?c
WHERE {
  VALUES ?type { owl:Class rdfs:Class }
  ?c a ?type .
  FILTER NOT EXISTS {
    # Gather all comments
    {
      VALUES ?commentProperty { rdfs:comment dcterms:description skos:definition }
      ?c ?commentProperty ?comment
    }
    UNION
    {
      ?c ?predicate ?comment .
      ?predicate a owl:AnnotationProperty ;
      rdfs:subPropertyOf* rdfs:comment .
    }
  }
  # exclude blank nodes
  FILTER(isIRI(?c))
  # Exclude deprecated classes
  FILTER NOT EXISTS {
    {
      ?c a owl:DeprecatedClass .
    }
    UNION
    {
      ?c owl:deprecated ?isDeprecated .
      FILTER(xsd:boolean(?isDeprecated))
    }
  }
}
