# Number of classes specified in NodeShapes
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT DISTINCT ?ns (COUNT(DISTINCT ?c) AS ?classCount)
WHERE {
  VALUES ?type { owl:Class rdfs:Class }
  {
    ?ns a sh:NodeShape, ?type .
    BIND (?ns as ?c)
  }
  UNION
  {
    ?ns a sh:NodeShape ;
          sh:targetClass ?c .
    ?c a ?type .
  }
} GROUP BY ?ns
