SELECT DISTINCT ?c
WHERE {
  VALUES ?type { owl:Class rdfs:Class }
  ?c a ?type .
  FILTER NOT EXISTS { 
    { ?c rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?lbl }
    UNION
    {
      ?c ?p ?lbl .
      ?p a owl:AnnotationProperty .
    }
  }
  # exclude blank nodes
  FILTER(isIRI(?c))
  # Exclude deprecated classes
  FILTER NOT EXISTS {
    ?c owl:deprecated ?isDeprecated .
    FILTER (?isDeprecated = true || LCASE(STR(?isDeprecated)) = "true" || STR(?isDeprecated) = "1")
  }
}

