SELECT DISTINCT ?c
WHERE {
  VALUES ?type { owl:Class rdfs:Class }
  ?c a ?type .
  FILTER NOT EXISTS {
    # Gather all comments
    {
      ?c rdfs:comment|dcterms:description|skos:definition ?lbl
    }
    UNION
    {
      ?c ?p ?lbl .
      ?p a owl:AnnotationProperty ;
      ?p rdfs:subPropertyOf* rdfs:comment .
    }
  }
  # exclude blank nodes
  FILTER(isIRI(?c))
  # Exclude deprecated classes
  FILTER NOT EXISTS {
    {
      ?c a owl:DeprecatedClass .
    }
    UNION
    {
      ?c owl:deprecated ?isDeprecated .
      FILTER(xsd:boolean(?isDeprecated))
    }
  }
}
