# Count the classes and properties in the current graph.
# To avoid unbound ?p when evaluating ?c (and vice versa), 
# two independent sub-SELECT blocks are specified, that both fire in the same solution.
# UNION is not used as it gives two rows.
SELECT  ?classCount ?propertyCount
WHERE {
 {
   SELECT (COUNT(DISTINCT ?class) AS ?classCount)
   WHERE {
    VALUES ?type { owl:Class rdfs:Class }
    ?class a ?type .
   }
 }
 {
   SELECT (COUNT(DISTINCT ?property) AS ?propertyCount)
   WHERE {
    {
      VALUES ?type { owl:ObjectProperty owl:DatatypeProperty rdf:Property owl:AnnotationProperty }
      ?property a ?type .
    }
    UNION
    {
      ?property rdfs:subClassOf+ rdf:Property
    }
    UNION
    {
      ?property rdfs:subPropertyOf ?parent
    }
   }
 }
}
