# Number of Deprecated Properties
# Count elements marked as deprecated

SELECT DISTINCT ?p
WHERE {
  { ?p a owl:DeprecatedProperty }
  UNION
  {
    ?p a ?type ;
    owl:deprecated ?o .
    VALUES ?type { owl:ObjectProperty rdf:Property owl:DatatypeProperty owl:AnnotationProperty }
  }
}
