# Number of Deprecated Classes
# Count elements marked as deprecated
SELECT DISTINCT ?c
WHERE {
  { ?c a owl:DeprecatedClass }
  UNION
  {
    ?c a ?type ;
    owl:deprecated ?o .
    VALUES ?type { owl:Class rdfs:Class }
  }
}
