# Number of Deprecated Properties
# Count elements marked as deprecated

SELECT DISTINCT ?p
WHERE {
  { ?p a owl:DeprecatedProperty }
  UNION
  {
    VALUES ?type { owl:ObjectProperty rdf:Property owl:DatatypeProperty owl:AnnotationProperty }
    ?p a ?type ;
    owl:deprecated ?isDeprecated .
    FILTER(xsd:boolean(?isDeprecated))
  }
}
