# Number of Deprecated Classes
# Count elements marked as deprecated
SELECT DISTINCT ?c
WHERE {
  { ?c a owl:DeprecatedClass }
  UNION
  {
    VALUES ?type { owl:Class rdfs:Class }
    ?c a ?type ;
    owl:deprecated ?isDeprecated .
    FILTER(xsd:boolean(?isDeprecated))
  }
}
