# Filter resources from external vocabularies.
# The result is a URI that has to be checked to points to a valid resource on the web.
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?resource
WHERE {
  # Resources declared as class
  {
    VALUES ?type { owl:Class rdfs:Class }
    ?resource a ?type .
  }
  UNION
  # Resources used as predicate
  {
    ?s ?resource ?o .
  }
  UNION
  # Resources used as object
  {
    ?s2 ?p ?resource .
  }
  # Filter resource URI from external namespaces
  ?ontology a owl:Ontology .
  FILTER(!CONTAINS(LCASE(STR(?resource)), LCASE(STR(?ontology))))
}
