PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?child ?parent
WHERE {
  # Check that child and parent are of the same type
  ?child a ?type ;
  rdfs:subClassOf ?parent .
  ?parent a ?type .
  FILTER(!isBlank(?child) && !isBlank(?parent))
} 

