SELECT (MAX(?depth) AS ?maxDepth)
WHERE {
    SELECT ?child (COUNT(DISTINCT ?parent) AS ?depth)
    WHERE {
        # Check that the entities are of the same type
        ?child a ?type .
        OPTIONAL {
            ?child rdfs:subClassOf+ ?parent .
            ?parent a ?type .
        }
    } GROUP BY ?child
}
