# Namespace hijacking
# Define a resource in the current namespace using an external vocabulary prefix.
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?resource
WHERE {
    ?resource ?property ?value .
    FILTER(isIRI(?resource))
    
    # Filter resource URI from external namespaces
    FILTER NOT EXISTS {
        VALUES ?type { owl:Ontology skos:ConceptScheme }
        ?namespace a ?type .
        BIND(REPLACE(STR(?namespace), "^(.{8,})[#/][^#/]*$", "$1") AS ?ns)
        FILTER(STRSTARTS(STR(?resource), ?ns))
    }
}