# Namespace hijacking
# Define a resource in the current namespace using an external vocabulary prefix.
SELECT DISTINCT ?resource
WHERE {
    ?resource ?property ?value .
    FILTER(isIRI(?resource))
    
    # Filter resource URI from external namespaces
    FILTER NOT EXISTS {
        VALUES ?type { owl:Ontology skos:ConceptScheme }
        ?namespace a ?type .
        FILTER(CONTAINS(LCASE(STR(?resource)), LCASE(STR(?namespace))))
    }
}
