# Number of Isolated Elements
# Classes declared but never used in any other triple connecting them to the rest of the ontology.
# TO DO: classes connected through properties defined in the current namespace.
SELECT DISTINCT ?c
WHERE {  
  VALUES ?type { owl:Class rdfs:Class }
  ?c a ?type .
  MINUS { ?c rdfs:subClassOf ?o }
  MINUS { ?s rdfs:subClassOf|rdfs:domain|rdfs:range|sh:targetClass|sh:class ?c }
  # FILTER NOT EXISTS {
  #   ?s rdfs:subClassOf|rdfs:domain|rdfs:range|sh:targetClass|sh:class ?o .
  #   FILTER(?c IN (?s, ?o))
  # }
}
