SELECT DISTINCT ?ns
WHERE {
  ?ns a sh:NodeShape .
  FILTER NOT EXISTS {
    # Gather all labels
    {
      VALUES ?labelProperty { rdfs:label skos:prefLabel skos:altLabel skos:hiddenLabel }
      ?ns ?labelProperty ?label
    }
    UNION
    {
      ?ns ?predicate ?label .
      ?predicate a owl:AnnotationProperty ;
      rdfs:subPropertyOf* rdfs:label .
    }
  }
}
