SELECT DISTINCT ?ns
WHERE {
  ?ns a sh:NodeShape .
  FILTER NOT EXISTS { 
    { ?ns rdfs:comment|dcterms:description|skos:definition [] }
    UNION
    {
      ?ns ?p [] .
      ?p a owl:AnnotationProperty .
    }
  }
}
