SELECT DISTINCT ?ns ?lbl
WHERE {
  ?ns a sh:NodeShape .
  # Gather all comments
  {
    ?ns rdfs:comment|dcterms:description|skos:definition ?lbl
  }
  UNION
  {
    ?ns ?p ?lbl .
    ?p a owl:AnnotationProperty ;
    ?p rdfs:subPropertyOf* rdfs:comment .
  }
}
