SELECT DISTINCT ?ns
WHERE {
  ?ns a sh:NodeShape .
  FILTER NOT EXISTS { 
    { ?ns rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?lbl }
    UNION
    {
      ?ns ?p ?lbl .
      ?p a owl:AnnotationProperty .
    }
  }
}
