SELECT DISTINCT ?ns ?lbl
WHERE {
  ?ns a sh:NodeShape .
  # Gather all labels
  {
    ?ns rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?lbl
  }
  UNION
  {
    ?ns ?p ?lbl .
    ?p a owl:AnnotationProperty ;
    ?p rdfs:subPropertyOf* rdfs:label .
  }
}
