PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?ont ?comment
WHERE {
  ?ont a owl:Ontology .
  {
    VALUES ?commentProperty { rdfs:comment dcterms:abstract dcterms:description skos:definition skos:note }
    ?ont ?commentProperty ?comment .
  }
  UNION
  {
    ?ont ?predicate ?comment .
    ?predicate a owl:AnnotationProperty ;
    rdfs:subPropertyOf* rdfs:comment .
  }
}
