SELECT ?ps ?label
WHERE {
    {
     	?ps a sh:PropertyShape  
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
    # Gather all labels
    {
      VALUES ?labelProperty { rdfs:label skos:prefLabel skos:altLabel skos:hiddenLabel }
      ?ps ?labelProperty ?label .
    }
    UNION
    {
      ?ps ?predicate ?label .
      ?predicate a owl:AnnotationProperty ;
      rdfs:subPropertyOf* rdfs:label .
    }
}
