SELECT DISTINCT ?ps
WHERE {
    {
     	?ps a sh:PropertyShape
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
    FILTER NOT EXISTS {
      # Gather all comments
      {
        ?ps rdfs:comment|dcterms:description|skos:definition ?lbl
      }
      UNION
      {
        ?ps ?predicate ?lbl .
        ?predicate a owl:AnnotationProperty ;
        ?predicate rdfs:subPropertyOf* rdfs:comment .
      }
    }
}
