PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT ?ps
WHERE {
    {
     	?ps a sh:PropertyShape  
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
    FILTER NOT EXISTS {
    # Gather all labels
    {
      VALUES ?labelProperty { rdfs:label skos:prefLabel skos:altLabel skos:hiddenLabel }
      ?ps ?labelProperty ?label .
    }
    UNION
    {
      ?ps ?predicate ?label .
      ?predicate a owl:AnnotationProperty ;
      rdfs:subPropertyOf* rdfs:label .
    }
  }
}
