SELECT DISTINCT ?p
WHERE {
  VALUES ?type { owl:ObjectProperty owl:DatatypeProperty rdf:Property }
  ?p a ?type .
  FILTER NOT EXISTS { ?p rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?lbl }
}
