PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT (COUNT(DISTINCT ?ps) AS ?shapeCount)
WHERE {
    {
     	?ps a sh:PropertyShape  
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
}
