SELECT DISTINCT ?p ?lbl
WHERE {
  VALUES ?type { owl:ObjectProperty owl:DatatypeProperty rdf:Property owl:AnnotationProperty }
  ?p a ?type .
  ?p rdfs:comment|dcterms:description|skos:definition ?lbl
}
