SELECT ?ps
WHERE {
    {
     	?ps a sh:PropertyShape  
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
    FILTER NOT EXISTS {
    # Gather all labels
    {
      ?ps rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?lbl
    }
    UNION
    {
      ?PropertyShape ?predicate ?lbl .
      ?predicate a owl:AnnotationProperty ;
      ?predicate rdfs:subPropertyOf* rdfs:label .
    }
  }
}
