SELECT DISTINCT ?ps
WHERE {
    {
     	?ps a sh:PropertyShape
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
    FILTER NOT EXISTS {
      # Gather all comments
      {
        VALUES ?commentProperty { rdfs:comment dcterms:description skos:definition }
        ?ps ?commentProperty ?comment .
      }
      UNION
      {
        ?ps ?predicate ?comment .
        ?predicate a owl:AnnotationProperty ;
        rdfs:subPropertyOf* rdfs:comment .
      }
    }
}
