PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT DISTINCT ?ps ?comment
WHERE {
    {
     	?ps a sh:PropertyShape  
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }
    # Gather all comments
    {
        VALUES ?commentProperty { rdfs:comment dcterms:description skos:definition }
        ?ps ?commentProperty ?comment .
    }
    UNION
    {
        ?ps ?predicate ?comment .
        ?predicate a owl:AnnotationProperty ;
        rdfs:subPropertyOf* rdfs:comment .
    }
}
