# PropertyShapes with the same label
SELECT ?label (GROUP_CONCAT(DISTINCT ?ps; separator=", ") AS ?psList)
WHERE {
    {
     	?ps a sh:PropertyShape
    } UNION {
      	?ns sh:property ?ps .
      	FILTER(isBlank(?ps)) .
    }

    # Gather all labels
    {
      ?ps rdfs:label|skos:prefLabel|skos:altLabel|skos:hiddenLabel ?label
    }
    UNION
    {
      ?PropertyShape ?predicate ?label .
      ?predicate a owl:AnnotationProperty ;
      ?predicate rdfs:subPropertyOf* rdfs:label .
    }
}
GROUP BY ?label
HAVING (COUNT(DISTINCT ?ps) > 1)
