PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
    ?instance ?predicate ?object .
}
WHERE {
	VALUES ?type { owl:Class rdfs:Class }
    ?class a ?type .
	?instance a ?class ;
	?predicate ?object .
	# Exclude meta modelling
	FILTER ( NOT EXISTS { ?instance a ?type } && NOT EXISTS { ?instance rdfs:subClassOf ?anything } )
}