# Non-unique identifiers
# Same IRI used for classes and/or properties
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?iri
  (GROUP_CONCAT(DISTINCT REPLACE(STR(?type), ".*/", ""); separator=", ") AS ?declaredAs)
WHERE {
  VALUES ?type { owl:Class rdfs:Class owl:ObjectProperty rdf:Property owl:DatatypeProperty  owl:AnnotationProperty }
  ?iri a ?type .

  FILTER NOT EXISTS { 
      ?iri a owl:Class . 
      FILTER(?type = rdfs:Class) 
  }
  FILTER NOT EXISTS { 
      ?iri a ?specificProperty .
      VALUES ?specificProperty { owl:ObjectProperty owl:DatatypeProperty owl:AnnotationProperty }
      FILTER(?type = rdf:Property) 
  }
}
GROUP BY ?iri
HAVING (COUNT(DISTINCT ?type) > 1)
