# Untyped property
# Property without rdf:Property, owl:ObjectProperty or owl:DatatypeProperty declaration
SELECT ?p
WHERE {
  # Get internal namespace
  { 
    SELECT (STR(?namespace) AS ?ns)
    WHERE { ?namespace a owl:Ontology . }
  }

  # Get predicates
  {
    SELECT DISTINCT ?p WHERE { ?s ?p ?o . FILTER(isIRI(?s)) }
  }

  # Restrict to ontology namespace
  FILTER(STRSTARTS(STR(?p), ?ns))

  # Filter out defined properties
  FILTER NOT EXISTS {
    VALUES ?type { rdf:Property owl:ObjectProperty owl:DatatypeProperty }
    ?p a ?type . 
  }
}
