# Untyped class
# Class without owl:Class or rdfs:Class declaration
SELECT DISTINCT ?c
WHERE {
  { ?s rdfs:domain ?c . }
  UNION
  { ?s rdfs:range ?c . }
  UNION
  { ?s sh:class ?c . }
  UNION
  { ?s rdfs:subClassOf ?c . }
  
  # exclude blank nodes
  FILTER(isIRI(?c))

  # Restrict to ontology namespace
  OPTIONAL {
    ?ontology a owl:Ontology .
    BIND(REPLACE(STR(?ontology), "^(.{8,})[#/][^#/]*$", "$1") AS ?ns)
  }
  FILTER (!BOUND(?ns) || STRSTARTS(STR(?c), ?ns))
  MINUS {
    VALUES ?type { owl:Class rdfs:Class rdfs:Datatype }
    ?c a ?type .
  }
}
