# Untyped class
# Class without owl:Class or rdfs:Class declaration
SELECT ?c
WHERE {
  # Get internal namespace
  { 
    SELECT (STR(?namespace) AS ?ns)
    WHERE { ?namespace a owl:Ontology . }
  }
  
  # Get objects
  {
    SELECT DISTINCT ?c
    WHERE {
      VALUES ?p { rdfs:domain rdfs:range sh:class }
      ?s ?p ?o .
      FILTER(isIRI(?o))
    }
  }

  # Restrict to ontology namespace
  FILTER(STRSTARTS(STR(?c), ?ns ))

  # Filter out defined classes
  FILTER NOT EXISTS {
    ?c a ?type .
    VALUES ?type { owl:Class rdfs:Class }
  }
}
