# Untyped property
# Property without rdf:Property, owl:ObjectProperty or owl:DatatypeProperty declaration
SELECT DISTINCT ?p
WHERE {
  # Find resources used as predicates
  ?s ?p ?o .

  # exclude blank nodes
  FILTER(isIRI(?s))

  # Restrict to ontology namespace
  OPTIONAL {
    ?ontology a owl:Ontology .
    BIND(REPLACE(STR(?ontology), "^(.{8,})[#/][^#/]*$", "$1") AS ?ns)
  }
  FILTER(STRSTARTS(STR(?p), ?ns))
  

  MINUS { ?p a rdf:Property }
  MINUS { ?p a owl:ObjectProperty }
  MINUS { ?p a owl:DatatypeProperty }

}
