# Ontolint configuration file: use it to enable or disable specific QA checks.
# Also allows users to ignore known unresolvable import URLs.
# Place this file as .rdf-lint.yml in your project root.

# Available checks:
# - class-missing-comment
# - class-missing-label
# - class-same-label
# - hijacking
# - isolated-classes
# - node-shape-missing-comment
# - node-shape-missing-label
# - node-shape-same-label
# - owl-declaration
# - owl-description
# - owl-imports
# - property-missing-comment
# - property-missing-domain
# - property-missing-label
# - property-missing-range
# - property-same-label
# - property-shape-missing-comment
# - property-shape-missing-label
# - property-shape-same-label
# - subclass-cycles
# - unique-identifiers
# - untyped-class
# - untyped-property

# Enable only specific checks (empty = all checks enabled)
# enable:
#   - owl-description
#   - class-missing-label
#   - property-missing-label

# Disable specific checks
# disable:
#   - hijacking
#   - isolated-classes
#   - property-missing-domain
        
# Exclude certain URLs from resolvability check. 
# Works on string matching, use URL only, do not include the ? or # at the end if pasting from a prefix.
# ignore-imports:
#   -  http://www.example.com
#   - http://www.w3.org/ns/shacl
#   - https://schema.org/
