PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# A collection of multiple SPARQL queries. Copy and Paste is your friend here.

SELECT DISTINCT ?c ?p WHERE {
    ?c a rdfs:Class .
    FILTER NOT EXISTS { ?c rdfs:label ?lbl   }
}


# 1.66
SELECT (AVG(?connectivity) AS ?averageConnectivity)
WHERE {
  {
    SELECT ?class (COUNT(DISTINCT ?link) AS ?connectivity)
    WHERE {
      ?class a owl:Class .
      {
        # subclass relationships
        { ?class rdfs:subClassOf ?link }
        UNION
        { ?link rdfs:subClassOf ?class }
        # object property domain/range usage
        UNION
        { ?prop a owl:ObjectProperty .
          ?prop rdfs:domain|rdfs:range ?class .
          BIND(?prop AS ?link)
        }
      }
    }
    GROUP BY ?class
  }
}

SELECT (AVG(?connectivity) AS ?averageConnectivity)
WHERE {
  {
    SELECT ?class (COUNT(DISTINCT ?link) AS ?connectivity)
    WHERE {
      VALUES ?type { owl:Class rdfs:Class }
	    ?class a ?type .
      {
        # subclass relationships
        { ?class rdfs:subClassOf ?link }
        UNION
        # superclass relationship
        { ?link rdfs:subClassOf ?class }
        #  domain/range usage
        UNION
        { ?prop rdfs:domain|rdfs:range ?class .
          BIND(?prop AS ?link)
        }
      }
    }
    GROUP BY ?class
  }
}

# Jeremy's connectivity
SELECT ?class (COUNT(DISTINCT ?prop) AS ?connectivity)
WHERE {
	VALUES ?type { owl:Class rdfs:Class }
	?class a ?type .
	OPTIONAL { ?prop rdfs:range ?class . }
	OPTIONAL {
		?class rdfs:subClassOf ?superClass .
		?superClass a owl:Class .
		?prop rdfs:range ?superClass
	}
} group by ?class


SELECT DISTINCT ?c
WHERE {
   { ?s rdf:type ?c . }
   UNION
   { ?s rdfs:domain ?c . }
   UNION
   { ?s rdfs:range ?c . }
  # Exclude built-in vocabulary
  FILTER (
    !regex(STR(?c), "http://www.w3.org/2002/07/owl#") &&
    !regex(STR(?c), "http://www.w3.org/2000/01/rdf-schema#") &&
    !regex(STR(?c), "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
  )
  # Exclude classes that are explicitly typed as owl:Class or rdfs:Class
  FILTER ( NOT EXISTS { ?c rdf:type owl:Class . } && NOT EXISTS { ?c rdf:type rdfs:Class . } )
}


# Property Shape Count
SELECT (COUNT(DISTINCT ?ps) AS ?shapeCount)
WHERE {
  ?ps a sh:PropertyShape .
}


SELECT DISTINCT ?ps ?prop
WHERE {
  ?ps a sh:PropertyShape .
  ?ps sh:path ?prop .
  VALUES ?type { owl:ObjectProperty rdf:Property owl:DatatypeProperty }
  ?prop a ?type .
}
