# Average Class Connectivity
# Note that this query misses the classes that are completely isolated (no links at all).
SELECT (AVG(?connectivity) AS ?averageConnectivity)
WHERE {
  {
    SELECT ?class (COUNT(DISTINCT ?link) AS ?connectivity)
    WHERE {
      VALUES ?type { owl:Class rdfs:Class }
      ?class a ?type .
      FILTER(isIRI(?class))
      {
        # subclass and superclass relationships
        {
          ?class rdfs:subClassOf ?link
        }
        UNION
        {
          ?link rdfs:subClassOf ?class 
        }
        # object property domain/range usage
        UNION
        { 
          VALUES ?predicate { rdfs:domain rdfs:range }
          ?s ?predicate ?class .
          BIND(?s AS ?link)
        }
      }
    }
    GROUP BY ?class
  }
}
