# Missing Domain or Range in Properties
# Properties without any rdfs:domain or rdfs:range declaration
SELECT DISTINCT ?property ?domain ?range
WHERE {
  VALUES ?type { owl:ObjectProperty owl:DatatypeProperty rdf:Property }
  ?property a ?type .
  OPTIONAL { ?property rdfs:domain ?domain }
  OPTIONAL { ?property rdfs:range  ?range  }
  FILTER( !BOUND(?domain) || !BOUND(?range) )
}
