SELECT DISTINCT ?ns ?comment
WHERE {
  ?ns a sh:NodeShape .
  # Gather all comments
  {
    VALUES ?commentProperty { rdfs:comment dcterms:description skos:definition }
    ?ns ?commentProperty ?comment
  }
  UNION
  {
    ?ns ?predicate ?comment .
    ?predicate a owl:AnnotationProperty ;
    rdfs:subPropertyOf* rdfs:comment .
  }
}
