# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Ontology QA

# Controls when the workflow will run
on: [push]

# The permissions granted to the GITHUB_TOKEN for this workflow
permissions:
  contents: read
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  validate:
    name: validate-ontology

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Cancel all in-progress and queued jobs in the matrix if any job in the matrix fails. 
    strategy:
      fail-fast: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Install dependencies
        run: poetry install
      
      - name: Check all ontologies
        run: | 
          poetry run scripts/ontology_qa.py tests/example.ttl -e --ctrf-dir ctrf -o /tmp/example.md
        if: always()

      - name: Generate CTRF report
        run: poetry run scripts/generate_custom_report.py --ctrf-dir ctrf --template-path templates/ctrf-report.hbs --output-path out/ctrf_report.md
        if: always()

      # Append report to workflow summary
      - name: Create workflow summary
        run: |
          cat out/ctrf_report.md >> $GITHUB_STEP_SUMMARY
        if: always()

      # Use peter-evans action to post or update a comment.
      - name: Comment with file contents
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: /tmp/example.md
        if: always()
